version: '3.8'
services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - dbdata:/data/db
      - ./MongoDB/init-data/01-create-db.js:/docker-entrypoint-initdb.d/01-create-db.js
    networks:
      - application

  mongo-seed:
    build:
      context: MongoDB
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - application

  influxdb:
    image: influxdb:latest
    ports:
      - '8086:8086'
    volumes:
      - influxDB_data:/var/lib/influxdb2
      - influxDB_config:/etc/influxdb2
    networks:
      - application
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=Theo
      - DOCKER_INFLUXDB_INIT_PASSWORD=12345678
      - DOCKER_INFLUXDB_INIT_ORG=HSGames
      - DOCKER_INFLUXDB_INIT_BUCKET=Inputs

  broadcaster:
    build:
      context: ./broadcaster
      dockerfile: Dockerfile
    ports:
      - 5000:5000
      - 80:80
    networks:
      - application

  api:
    build:
      context: ./API
      dockerfile: Dockerfile

    ports:
      - 4000:4000
    networks:
      - application
    depends_on:
      - mongodb
      - influxdb

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/:/www/
    ports:
      - 8051:80
    networks:
      - application

volumes:
  dbdata:
  influxDB_data:
  influxDB_config:


networks:
  application:
